---
name: clang 18

"on":
  push:
    branches:
      - main
      - devel
  pull_request:


jobs:
  automake:
    name: Compiles with clang 18, using automake
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install packages
        run: sudo apt install build-essential nettle-dev time clang-18
      - name: bootstrap
        run: ./bootstrap.sh
      - name: configure
        run: ./configure CXX=clang++-18
      - name: build
        run: make
      - name: check
        run: make check
      - name: store the logs as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          path: '**/*.log'

  cmake:
    name: Compiles with clang 18, using cmake
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install packages
        run: |
          sudo apt install \
            build-essential \
            cmake \
            nettle-dev \
            libxxhash-dev \
            catch2 \
            time \
            clang-18
      - name: configure
        run: |
          cmake \
            -B build \
            -S inofficial_cmake/ \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=On \
            -DCMAKE_CXX_COMPILER=clang++-18
      - name: build
        run: cmake --build build
      - name: test
        run: ctest --test-dir build --output-on-failure
