---
name: debian 14 forky

"on":
  push:
    branches:
      - main
      - devel
  pull_request:


jobs:
  container-automake:
    name: automake
    runs-on: ubuntu-latest
    container:
      image: debian:forky-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install packages
        run: apt-get update && apt-get install autoconf build-essential nettle-dev libxxhash-dev libcap2-bin --yes
      - name: bootstrap
        run: ./bootstrap.sh
      - name: configure
        run: ./configure --enable-warnings CXXFLAGS=-std=c++17
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck CXXFLAGS=-std=c++17
      - name: build with hardened build flags
        run: |
          make clean
          eval $(DEB_CXXFLAGS_APPEND=-std=c++17 DEB_BUILD_MAINT_OPTIONS="hardening=+all qa=+all,-canary reproducible=+all" dpkg-buildflags --export=sh)
          ./configure
          make
          make check
      - name: store the logs as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          path: '**/*.log'
          name: 'automake logs'

  container-cmake:
    name: cmake
    runs-on: ubuntu-latest
    container:
      image: debian:forky-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install packages
        run: apt-get update && apt-get install cmake pkgconf build-essential nettle-dev libcap2-bin --yes
      - name: configure
        run: cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=On -B build -S inofficial_cmake/
      - name: build
        run: cmake --build build
      - name: test
        run: ctest --test-dir build --output-on-failure
      - name: store cmake logs as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          path: '**/*.log'
          name: 'cmake logs'
